# fly.toml app configuration file generated for social-app-silent-dust-7511 on 2025-09-25T18:39:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'social-app-silent-dust-7511'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
